In [1]:
import geopandas as gpd
import fiona
import pandas as pd
import pickle

In [ ]:

# Path to the files
# path = "/hadatasets/nui_precarious_settlements/"

#grid = gpd.read_file(path + "POLOS_GRADE_rev.gpkg")

In [ ]:
#with open("grid.pkl", "wb") as f:
#    pickle.dump(grid, f)

In [2]:
with open("grid.pkl", "rb") as f:
    grid = pickle.load(f)

In [3]:
path = "/hadatasets/nui_precarious_settlements/"
nui = gpd.read_file(path + "POLOS_NUIS.gpkg", engine="fiona")

In [4]:
nui

,V0,V1,V2a,V2b,V3a,V3b,V4a,V4b,V4c,V5a,...,V14a,V14b,V15a,V15b,V16a,V16b,V17,V18,V19,geometry
0,NUI2507,Porto Alegre,Gravataí,Grupo 2,Parque Do Sol,1,40.0,Prefeitura,2017,1.0,...,1.0,None,1.0,None,1.0,None,1.0,None,até 50,"MULTIPOLYGON (((-51.05983 -29.94914, -51.05964..."
1,NUI2508,Porto Alegre,Gravataí,Grupo 2,Miraflores,1,504.0,Prefeitura,2017,2.0,...,1.0,None,1.0,None,1.0,None,2.0,None,de 100 a 700,"MULTIPOLYGON (((-51.04300 -29.87690, -51.04210..."
2,NUI2509,Porto Alegre,Gravataí,Grupo 2,Cruzeiro Ii_Rua Zaire,1,130.0,Prefeitura,2017,1.0,...,2.0,None,2.0,None,2.0,None,2.0,None,de 100 a 700,"MULTIPOLYGON (((-51.05244 -29.95080, -51.05115..."
3,NUI2510,Porto Alegre,Gravataí,Grupo 2,Cruzeiro Ii_Rua Venezuela,1,16.0,Prefeitura,2017,1.0,...,2.0,None,4.0,None,2.0,None,2.0,None,até 50,"MULTIPOLYGON (((-51.05375 -29.94861, -51.05238..."
4,NUI2511,Porto Alegre,Gravataí,Grupo 2,Parque Florido,1,117.0,Prefeitura,2017,1.0,...,3.0,None,4.0,None,2.0,None,2.0,None,de 100 a 700,"MULTIPOLYGON (((-51.06033 -29.93802, -51.06046..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4963,NUI3984,Recife,Ipojuca,Grupo 3,ZEIS Capim Verde,1,104.0,CADUNICO,2020,1.0,...,4.0,None,4.0,None,2.0,None,2.0,None,de 100 a 700,"MULTIPOLYGON (((-35.06065 -8.40016, -35.06056 ..."
4964,NUI3965,Recife,Ipojuca,Grupo 3,Invasão Maracaípe,1,5.0,Censo IBGE,2010,1.0,...,4.0,None,4.0,None,4.0,None,3.0,Ocupação da área de mata ciliar de curso d'água,até 50,"MULTIPOLYGON (((-35.01137 -8.53032, -35.01117 ..."
4965,NUI3981,Recife,Ipojuca,Grupo 3,ZEIS Bela Vista,1,331.0,Censo IBGE,2010,1.0,...,4.0,None,4.0,None,4.0,None,2.0,Ocupação em área de alto declividade,de 100 a 700,"MULTIPOLYGON (((-35.07562 -8.41341, -35.07534 ..."
4966,NUI3982,Recife,Ipojuca,Grupo 3,ZEIS Califórnia,1,10.0,Censo IBGE,2010,1.0,...,4.0,None,4.0,None,2.0,None,2.0,None,até 50,"MULTIPOLYGON (((-35.04375 -8.39069, -35.04343 ..."
4967,NUI0455,Belo Horizonte,Betim,Grupo 1,Guanabara,3.PLHIS,40.0,PLHIS,2012,1.0,...,1.0,None,1.0,None,2.0,Heterogêno,1.0,None,até 50,"MULTIPOLYGON (((-44.13600 -19.96879, -44.13182..."

In [9]:
grid

,gid,ID,UF,Col,Row,Polo,Declividade,Curvatura,APP30m,UCIntegral,...,t_vulner_mais1h,t_renda_trab,t_carteira_18m,t_scarteira_18m,t_setorpublico_18m,t_contapropria_18m,t_empregador_18m,t_formal_18m,t_atividade10a15,geometry
0,100ME5208050N7956750,C10L1067,RS,10.0,1067.0,Porto Alegre,4.919002,6.333333,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((5208000.000 7956700.000, 5208100.000..."
1,100ME5208050N7956850,C10L1068,RS,10.0,1068.0,Porto Alegre,4.900816,1.000000,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((5208000.000 7956800.000, 5208100.000..."
2,100ME5208050N7956950,C10L1069,RS,10.0,1069.0,Porto Alegre,4.152381,4.666667,0.333333,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((5208000.000 7956900.000, 5208100.000..."
3,100ME5208150N7956750,C11L1067,RS,11.0,1067.0,Porto Alegre,3.205212,7.777778,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((5208100.000 7956700.000, 5208200.000..."
4,100ME5208150N7956850,C11L1068,RS,11.0,1068.0,Porto Alegre,5.218916,4.166667,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((5208100.000 7956800.000, 5208200.000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735153,100ME7090650N10419450,C896L1164,PE,896.0,1164.0,Recife,1.944661,3.511628,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((7090600.000 10419400.000, 7090700.00..."
735154,100ME7090650N10419550,C896L1165,PE,896.0,1165.0,Recife,3.191298,3.777778,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((7090600.000 10419500.000, 7090700.00..."
735155,100ME7090650N10419650,C896L1166,PE,896.0,1166.0,Recife,1.246800,1.888889,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((7090600.000 10419600.000, 7090700.00..."
735156,100ME7090650N10419750,C896L1167,PE,896.0,1167.0,Recife,1.599806,1.418605,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((7090600.000 10419700.000, 7090700.00..."
735157,100ME7090650N10419850,C896L1168,PE,896.0,1168.0,Recife,1.291296,5.382979,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((7090600.000 10419800.000, 7090700.00..."

In [10]:
len(grid)

735158

In [12]:
intersection = gpd.overlay(nui[["V5a", "geometry"]].to_crs(grid.crs), grid, how="intersection")
t2 = gpd.overlay(nui[["V5a", "geometry"]].to_crs(grid.crs), grid, how="difference")

In [13]:

print(len(intersection))

131595

In [ ]:
df_grid = grid

,gid,ID,UF,Col,Row,Polo,Declividade,Curvatura,APP30m,UCIntegral,...,t_nremunerado_18m,t_vulner_mais1h,t_renda_trab,t_carteira_18m,t_scarteira_18m,t_setorpublico_18m,t_contapropria_18m,t_empregador_18m,t_formal_18m,t_atividade10a15
0,100ME5208050N7956750,C10L1067,RS,10.0,1067.0,Porto Alegre,4.919002,6.333333,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100ME5208050N7956850,C10L1068,RS,10.0,1068.0,Porto Alegre,4.900816,1.000000,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100ME5208050N7956950,C10L1069,RS,10.0,1069.0,Porto Alegre,4.152381,4.666667,0.333333,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100ME5208150N7956750,C11L1067,RS,11.0,1067.0,Porto Alegre,3.205212,7.777778,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100ME5208150N7956850,C11L1068,RS,11.0,1068.0,Porto Alegre,5.218916,4.166667,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735153,100ME7090650N10419450,C896L1164,PE,896.0,1164.0,Recife,1.944661,3.511628,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735154,100ME7090650N10419550,C896L1165,PE,896.0,1165.0,Recife,3.191298,3.777778,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735155,100ME7090650N10419650,C896L1166,PE,896.0,1166.0,Recife,1.246800,1.888889,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735156,100ME7090650N10419750,C896L1167,PE,896.0,1167.0,Recife,1.599806,1.418605,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735157,100ME7090650N10419850,C896L1168,PE,896.0,1168.0,Recife,1.291296,5.382979,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_grid["target"] = 0
intersection = intersection.rename({"V5a": "target"}, axis=1).drop(["geometry"], axis=1).drop_duplicates()

In [ ]:
intersection.columns

Index(['target', 'gid', 'ID', 'UF', 'Col', 'Row', 'Polo', 'Declividade',
       'Curvatura', 'APP30m',
       ...
       't_nremunerado_18m', 't_vulner_mais1h', 't_renda_trab',
       't_carteira_18m', 't_scarteira_18m', 't_setorpublico_18m',
       't_contapropria_18m', 't_empregador_18m', 't_formal_18m',
       't_atividade10a15'],
      dtype='object', length=116)

In [17]:
df_grid.columns

Index(['gid', 'ID', 'UF', 'Col', 'Row', 'Polo', 'Declividade', 'Curvatura',
       'APP30m', 'UCIntegral',
       ...
       't_renda_trab', 't_carteira_18m', 't_scarteira_18m',
       't_setorpublico_18m', 't_contapropria_18m', 't_empregador_18m',
       't_formal_18m', 't_atividade10a15', 'geometry', 'target'],
      dtype='object', length=117)

In [18]:
df_grid = df_grid.drop(["geometry"], axis=1)

In [25]:
intersection = intersection.groupby('gid').apply(lambda group: group.sample(1)).reset_index(drop=True)

In [26]:
missing_ids = pd.merge(intersection["gid"], df_grid, on='gid', how='right', indicator=True)

In [27]:
len(missing_ids)

735158

In [28]:
result_df = missing_ids[missing_ids['_merge'] == 'right_only'].drop(['_merge'], axis=1)
multi_class_grid = pd.concat([intersection, result_df], ignore_index=True)

In [ ]:
len(multi_class_grid)

735158

In [30]:
multi_class_grid.to_csv("multi_class_grid.csv")